// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherScheduler.Models;

#nullable disable

namespace WeatherScheduler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230906005351_CreateSchemaAndBaseDataToDb")]
    partial class CreateSchemaAndBaseDataToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherScheduler.Models.City", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Name = "Tokyo",
                            Latitude = 35.689500000000002,
                            longitude = 139.6917
                        },
                        new
                        {
                            Name = "Osaka",
                            Latitude = 34.6937,
                            longitude = 135.50219999999999
                        },
                        new
                        {
                            Name = "Sapporo",
                            Latitude = 43.066699999999997,
                            longitude = 141.34999999999999
                        },
                        new
                        {
                            Name = "LosAngeles",
                            Latitude = 34.052199999999999,
                            longitude = -118.2437
                        },
                        new
                        {
                            Name = "NewYork",
                            Latitude = 56.25,
                            longitude = -5.2832999999999997
                        },
                        new
                        {
                            Name = "SanFrancisco",
                            Latitude = 37.774900000000002,
                            longitude = 122.4194
                        },
                        new
                        {
                            Name = "DaNang",
                            Latitude = 16.067799999999998,
                            longitude = 108.2208
                        },
                        new
                        {
                            Name = "DaLat",
                            Latitude = 11.9465,
                            longitude = 108.4419
                        },
                        new
                        {
                            Name = "Hanoi",
                            Latitude = 21.0245,
                            longitude = 105.8412
                        },
                        new
                        {
                            Name = "ChiangMai",
                            Latitude = 18.790400000000002,
                            longitude = 98.984700000000004
                        },
                        new
                        {
                            Name = "Phuket",
                            Latitude = 7.8906000000000001,
                            longitude = 98.398099999999999
                        },
                        new
                        {
                            Name = "Boracay",
                            Latitude = 11.9801,
                            longitude = 121.91930000000001
                        },
                        new
                        {
                            Name = "Cebu",
                            Latitude = 10.333299999999999,
                            longitude = 123.75
                        },
                        new
                        {
                            Name = "PulauUbin",
                            Latitude = 1.4118999999999999,
                            longitude = 103.9639
                        },
                        new
                        {
                            Name = "Woodlands",
                            Latitude = 1.4379999999999999,
                            longitude = 103.78879999999999
                        },
                        new
                        {
                            Name = "Tampines",
                            Latitude = 1.3581000000000001,
                            longitude = 103.94029999999999
                        },
                        new
                        {
                            Name = "Guam",
                            Latitude = 13.4786,
                            longitude = 144.81829999999999
                        },
                        new
                        {
                            Name = "Ulaanbaatar",
                            Latitude = 47.907699999999998,
                            longitude = 106.8832
                        },
                        new
                        {
                            Name = "Darkhan",
                            Latitude = 49.486699999999999,
                            longitude = 105.9228
                        },
                        new
                        {
                            Name = "Kharkhorin",
                            Latitude = 47.192500000000003,
                            longitude = 102.8135
                        },
                        new
                        {
                            Name = "Berlin",
                            Latitude = 52.5244,
                            longitude = 13.410500000000001
                        },
                        new
                        {
                            Name = "Munich",
                            Latitude = 48.1374,
                            longitude = 11.5755
                        },
                        new
                        {
                            Name = "Frankfurt ",
                            Latitude = 49.683300000000003,
                            longitude = 10.533300000000001
                        },
                        new
                        {
                            Name = "Istanbul",
                            Latitude = 41.013800000000003,
                            longitude = 28.9497
                        },
                        new
                        {
                            Name = "Antalya ",
                            Latitude = 36.908099999999997,
                            longitude = 30.695599999999999
                        },
                        new
                        {
                            Name = "Bodrum ",
                            Latitude = 37.0383,
                            longitude = 27.429200000000002
                        },
                        new
                        {
                            Name = "Paris",
                            Latitude = 48.8566,
                            longitude = 2.3521999999999998
                        },
                        new
                        {
                            Name = "London",
                            Latitude = 51.507399999999997,
                            longitude = -0.1278
                        },
                        new
                        {
                            Name = "Rome",
                            Latitude = 41.902799999999999,
                            longitude = 12.4964
                        },
                        new
                        {
                            Name = "Madrid",
                            Latitude = 40.416800000000002,
                            longitude = -3.7038000000000002
                        },
                        new
                        {
                            Name = "Sydney",
                            Latitude = -33.865099999999998,
                            longitude = 151.20930000000001
                        },
                        new
                        {
                            Name = "Rio de Janeiro",
                            Latitude = -22.9068,
                            longitude = -43.172899999999998
                        },
                        new
                        {
                            Name = "Cairo",
                            Latitude = 30.0444,
                            longitude = 31.235700000000001
                        },
                        new
                        {
                            Name = "Bangkok",
                            Latitude = 13.7563,
                            longitude = 100.5018
                        },
                        new
                        {
                            Name = "Seoul",
                            Latitude = 37.566499999999998,
                            longitude = 126.97799999999999
                        },
                        new
                        {
                            Name = "Beijing",
                            Latitude = 39.904200000000003,
                            longitude = 116.4074
                        },
                        new
                        {
                            Name = "Shanghai",
                            Latitude = 31.230399999999999,
                            longitude = 121.47369999999999
                        },
                        new
                        {
                            Name = "Moscow",
                            Latitude = 55.755800000000001,
                            longitude = 37.617600000000003
                        },
                        new
                        {
                            Name = "Athens",
                            Latitude = 37.983800000000002,
                            longitude = 23.727499999999999
                        },
                        new
                        {
                            Name = "Cape Town",
                            Latitude = -33.924900000000001,
                            longitude = 18.424099999999999
                        },
                        new
                        {
                            Name = "Toronto",
                            Latitude = 43.651069999999997,
                            longitude = -79.347014999999999
                        },
                        new
                        {
                            Name = "Vancouver",
                            Latitude = 49.282699999999998,
                            longitude = -123.1207
                        },
                        new
                        {
                            Name = "Chicago",
                            Latitude = 41.878100000000003,
                            longitude = -87.629800000000003
                        },
                        new
                        {
                            Name = "San Diego",
                            Latitude = 32.715699999999998,
                            longitude = -117.1611
                        },
                        new
                        {
                            Name = "Dallas",
                            Latitude = 32.776699999999998,
                            longitude = -96.796999999999997
                        },
                        new
                        {
                            Name = "Miami",
                            Latitude = 25.761700000000001,
                            longitude = -80.191800000000001
                        },
                        new
                        {
                            Name = "Orlando",
                            Latitude = 28.5383,
                            longitude = -81.379199999999997
                        },
                        new
                        {
                            Name = "New Orleans",
                            Latitude = 29.9511,
                            longitude = -90.0715
                        },
                        new
                        {
                            Name = "Las Vegas",
                            Latitude = 36.169899999999998,
                            longitude = -115.13979999999999
                        },
                        new
                        {
                            Name = "San Antonio",
                            Latitude = 29.424099999999999,
                            longitude = -98.493600000000001
                        },
                        new
                        {
                            Name = "Austin",
                            Latitude = 30.267199999999999,
                            longitude = -97.743099999999998
                        },
                        new
                        {
                            Name = "Denver",
                            Latitude = 39.739199999999997,
                            longitude = -104.9903
                        },
                        new
                        {
                            Name = "Phoenix",
                            Latitude = 33.448399999999999,
                            longitude = -112.074
                        },
                        new
                        {
                            Name = "Portland",
                            Latitude = 45.505099999999999,
                            longitude = -122.675
                        },
                        new
                        {
                            Name = "Seattle",
                            Latitude = 47.606200000000001,
                            longitude = -122.3321
                        },
                        new
                        {
                            Name = "Honolulu",
                            Latitude = 21.306899999999999,
                            longitude = -157.85830000000001
                        },
                        new
                        {
                            Name = "Anchorage",
                            Latitude = 61.2181,
                            longitude = -149.90029999999999
                        },
                        new
                        {
                            Name = "Montreal",
                            Latitude = 45.5017,
                            longitude = -73.567300000000003
                        },
                        new
                        {
                            Name = "Quebec City",
                            Latitude = 46.813899999999997,
                            longitude = -71.207999999999998
                        },
                        new
                        {
                            Name = "Halifax",
                            Latitude = 44.648800000000001,
                            longitude = -63.575200000000002
                        },
                        new
                        {
                            Name = "Ottawa",
                            Latitude = 45.421500000000002,
                            longitude = -75.690600000000003
                        },
                        new
                        {
                            Name = "Winnipeg",
                            Latitude = 49.895099999999999,
                            longitude = -97.138400000000004
                        },
                        new
                        {
                            Name = "Regina",
                            Latitude = 50.4452,
                            longitude = -104.6189
                        },
                        new
                        {
                            Name = "Saskatoon",
                            Latitude = 52.133200000000002,
                            longitude = -106.67
                        },
                        new
                        {
                            Name = "Calgary",
                            Latitude = 51.044699999999999,
                            longitude = -114.0719
                        },
                        new
                        {
                            Name = "Edmonton",
                            Latitude = 53.544400000000003,
                            longitude = -113.4909
                        },
                        new
                        {
                            Name = "Mexico City",
                            Latitude = 19.432600000000001,
                            longitude = -99.133200000000002
                        },
                        new
                        {
                            Name = "Santiago",
                            Latitude = -33.448900000000002,
                            longitude = -70.669300000000007
                        },
                        new
                        {
                            Name = "Lima",
                            Latitude = -12.0464,
                            longitude = -77.0428
                        },
                        new
                        {
                            Name = "Bogota",
                            Latitude = 4.7108999999999996,
                            longitude = -74.072100000000006
                        },
                        new
                        {
                            Name = "Caracas",
                            Latitude = 10.488,
                            longitude = -66.879199999999997
                        },
                        new
                        {
                            Name = "Sao Paulo",
                            Latitude = -23.5505,
                            longitude = -46.633299999999998
                        },
                        new
                        {
                            Name = "Buenos Aires",
                            Latitude = -34.611800000000002,
                            longitude = -58.417299999999997
                        },
                        new
                        {
                            Name = "Brasilia",
                            Latitude = -15.780099999999999,
                            longitude = -47.929200000000002
                        },
                        new
                        {
                            Name = "Belo Horizonte",
                            Latitude = -19.916699999999999,
                            longitude = -43.9345
                        },
                        new
                        {
                            Name = "Monterrey",
                            Latitude = 25.686599999999999,
                            longitude = -100.31610000000001
                        },
                        new
                        {
                            Name = "Guadalajara",
                            Latitude = 20.659700000000001,
                            longitude = -103.3496
                        },
                        new
                        {
                            Name = "Montevideo",
                            Latitude = -34.9011,
                            longitude = -56.191000000000003
                        },
                        new
                        {
                            Name = "Asuncion",
                            Latitude = -25.2637,
                            longitude = -57.575899999999997
                        },
                        new
                        {
                            Name = "Mumbai",
                            Latitude = 19.076000000000001,
                            longitude = 72.877700000000004
                        },
                        new
                        {
                            Name = "Delhi",
                            Latitude = 28.613900000000001,
                            longitude = 77.209000000000003
                        },
                        new
                        {
                            Name = "Kolkata",
                            Latitude = 22.572600000000001,
                            longitude = 88.363900000000001
                        },
                        new
                        {
                            Name = "Bangalore",
                            Latitude = 12.9716,
                            longitude = 77.5946
                        },
                        new
                        {
                            Name = "Chennai",
                            Latitude = 13.082700000000001,
                            longitude = 80.270700000000005
                        },
                        new
                        {
                            Name = "Hyderabad",
                            Latitude = 17.385000000000002,
                            longitude = 78.486699999999999
                        },
                        new
                        {
                            Name = "Pune",
                            Latitude = 18.520399999999999,
                            longitude = 73.856700000000004
                        },
                        new
                        {
                            Name = "Ahmedabad",
                            Latitude = 23.022500000000001,
                            longitude = 72.571399999999997
                        },
                        new
                        {
                            Name = "Kuala Lumpur",
                            Latitude = 3.1389999999999998,
                            longitude = 101.68689999999999
                        },
                        new
                        {
                            Name = "Singapore",
                            Latitude = 1.3521000000000001,
                            longitude = 103.8198
                        },
                        new
                        {
                            Name = "Jakarta",
                            Latitude = -6.2088000000000001,
                            longitude = 106.8456
                        },
                        new
                        {
                            Name = "Manila",
                            Latitude = 14.599500000000001,
                            longitude = 120.9842
                        },
                        new
                        {
                            Name = "Ho Chi Minh City",
                            Latitude = 10.776899999999999,
                            longitude = 106.7
                        },
                        new
                        {
                            Name = "Granada",
                            Latitude = 37.177300000000002,
                            longitude = -3.5985999999999998
                        },
                        new
                        {
                            Name = "Malaga",
                            Latitude = 36.7196,
                            longitude = -4.4199999999999999
                        },
                        new
                        {
                            Name = "Palma de Mallorca",
                            Latitude = 39.569600000000001,
                            longitude = 2.6501999999999999
                        },
                        new
                        {
                            Name = "Ibiza",
                            Latitude = 38.908499999999997,
                            longitude = 1.427
                        });
                });

            modelBuilder.Entity("WeatherScheduler.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Pwd")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NickName = "Admin",
                            Pwd = 123456789
                        });
                });

            modelBuilder.Entity("WeatherScheduler.Models.Schedule", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("No");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            No = 1,
                            Content = "3박 4일 오사카 여행",
                            DateTime = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID = "강동우",
                            Title = "오사카 여행"
                        },
                        new
                        {
                            No = 2,
                            Content = "5박6일 괌 여행",
                            DateTime = new DateTime(2023, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2023, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID = "안병길",
                            Title = "괌 여행"
                        },
                        new
                        {
                            No = 3,
                            Content = "4박5일 치앙마이 여행",
                            DateTime = new DateTime(2023, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID = "주영준",
                            Title = "치앙마이 여행"
                        },
                        new
                        {
                            No = 4,
                            Content = "6박7일 뉴욕 여행",
                            DateTime = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ID = "홍승현",
                            Title = "뉴욕 여행"
                        });
                });

            modelBuilder.Entity("WeatherScheduler.Models.Weather", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<string>("WeatherState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
